name: Nexus Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Run Translator
        run: |
          python tools/translator/ingest.py
      - name: Render Diagrams
        run: |
          python -m tools.nexus render
      - name: Run PR Gate
        run: |
          python -m tools.nexus gate
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nexus-artifacts
          path: |
            artifacts/
            .artifacts/
